fun main() {
    
    val b = 10;
    val c = 5; 
    
    val soma = b + c
    println("A soma de A mais B é: " + soma)
    println()
 
    
    val subtração = b - c
    println("A subtração de A menos B é: " + subtração)
    println()
    
    val divisão = b / c
    println("A divisão de A com B é: " + divisão)
    println()
    
    val multiplicação = b * c
    println("A multiplicação de A com B é: " + multiplicação)
    println()
}